name: config_core
description: Core configuration logic, schema, validation, and persistence.
version: 0.0.1
resolution: workspace
publish_to: none

environment:
  sdk: ">=3.10.7 <4.0.0"

dependencies:
  path_provider: ^2.1.0
  equatable: ^2.0.8
  json_annotation: ^4.10.0
  flutter_riverpod: ^3.2.1
  watcher: ^1.1.0
  yaml: ^3.1.2
  path: ^1.9.1
  copy_with_extension: ^11.0.0

dev_dependencies:
  build_runner: ^2.4.0
  json_serializable: ^6.12.0
  test: ^1.29.0
  lints: ^6.0.0
  copy_with_extension_gen: ^11.0.0
