[package]
name = "nma_gapp_rs"
version = "0.1.0"
edition = "2021"

[dependencies]
winit = {"version" = "0.30.12"}
flutter-embedder-sys = {"path" = "../flutter-embedder-sys"}
glutin = "0.32.3"
glutin-winit = "0.5.0"
raw-window-handle = "0.6.2"
