name: provider_mock
description: Mock implementation of the Chat Provider API for testing and development.
version: 0.0.1
resolution: workspace
publish_to: none

environment:
  sdk: ^3.10.7

dependencies:
  provider_api: any

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
